### ISSUE TITLE
Logo Proporsal

### ISSUE THREAD

**Issue by tjulises** [BT-OpenSource/bt-openlink-java#22]
Hey, I'm graphic designer and my aim is supporting open source projects and make my portfolio better. So, I can contribute on your project with making logo design. I am waiting your feedback! Have a nice day! :)

Best Regards,
TJ Ulises
Visual Communication Designer

**Comment by GregDThomas** [comment]
Thanks for your offer, but we're not looking for a logo at this time.

Regards,

Greg
